apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-app-deployment
  namespace: planning-app-deployment
  labels:
    app: planning-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: planning-app-deployment
  template:
    metadata:
      labels:
        app: planning-app-deployment
    spec:
      containers:
        - name: planning-app-deployment
          image: blessedmine/planning-app-deployment:v2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 300Mi