apiVersion: v1
kind: Service
metadata:
  name: planning-app-deployment
spec:
  selector:
    app: planning-app-deployment
  ports:
    - protocol: TCP
      port: 80 # The port the service is exposed on
      targetPort: 80 # The port your application is listening on